### ISSUE TITLE
Can't mock object methods with boolen return types

### ISSUE THREAD

**Issue by ctrlaltdylan** [Codeception/MockeryModule#10] opened 2016-02-05 14:42 UTC
Unable to mock any methods that have a boolean return type. Need to do more research to see if it's breaking on other primitives.

Example:

```
public function toBeTested() : bool
{
   return true;
}
```

The mocked version does not include the `bool` return type and breaks.

**Comment by enumag** [comment] 2016-02-05 22:33
Is it just the bool type or other types as well? See https://github.com/padraic/mockery/issues/511.

Anyway this is probably not relevant to this package. This is just an itegration of Mockery to Codeception. The bug itself is most likely in Mockery.

I suggest trying the master branch of Mockery and if it doesn't help, report an issue in the Mockery repository (although it is possibly a duplicate of the issue I linked above).

**Closed by enumag** 2016-02-05 22:33 UTC

**Comment by devartbvba** [comment] 2016-05-25 11:33
Would it be possible to use dev-master of Mockery to address the php7 return type issue? Mockery has fixed the issue but has not released it, they suggest to use dev-master until than, but the MockeryModule prevents us fro doing that...

**Comment by enumag** [comment] 2016-05-25 11:38
@devartbvba Try this in your composer.json, it should install then.

```
 "mockery/mockery": "dev-master as 0.9.99",
```

Let me know if everything works with master mockery. If it does I'll add mockery 1.0 to allowed versions.

**Comment by devartbvba** [comment] 2016-05-25 13:34
Well that's kind of the root of the problem, there is no Mockery 1.0 (yet). The reason for that is that they have made backwards incompatible changes so there won't be a ~0.x release anymore.

So what I'd advise is to bump the MockeryModule to a new major version before adding mockery 1.x to your module as it will break some peoples tests...

**Comment by enumag** [comment] 2016-05-25 13:38
Actualy there is mockery 1.0, it just isn't stable. After I make the change it will be possible to install it like this:

```
"mockery/mockery": "^1.0@dev",
```

Well you should have both this package and mockery among your dependencies which would avoid the issue but yeah I'll do as you say - when Mockery 1.0 is stable.

**Comment by devartbvba** [comment] 2016-05-25 13:40
Okay!

For now I fixed it with the alias as you suggested, works as expected (dev-master was pulled in afterwards), thanks for the advice
